### ISSUE TITLE
error in when i run train.py

### ISSUE THREAD

**Issue by lnuchiyo** [CharlesShang/FastMaskRCNN#106]
when i run train.py，there si error"out of memory". but my memory is 16GB, and the hard disk space is 150+GB.and this error say:Total memory: 1.95GiB      Free memory: 1.70GiB
total output as follow:

P2
P3
P4
P5
/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2017-07-13 08:23:17.300977: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-13 08:23:17.300999: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-13 08:23:17.301004: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-13 08:23:17.301007: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-13 08:23:17.301010: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-07-13 08:23:17.508313: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-07-13 08:23:17.508536: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties:
name: Quadro K620
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:01:00.0
Total memory: 1.95GiB
Free memory: 1.70GiB
2017-07-13 08:23:17.508562: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0
2017-07-13 08:23:17.508566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y
2017-07-13 08:23:17.508571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro K620, pci bus id: 0000:01:00.0)
2017-07-13 08:23:17.510416: E tensorflow/stream_executor/cuda/cuda_driver.cc:893] failed to allocate 1.86G (1992916992 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
--restore_previous_if_exists is set, but failed to restore in ./output/mask_rcnn/ None
restoring  resnet_v1_50/conv1/weights:0
restoring  resnet_v1_50/conv1/BatchNorm/beta:0
restoring  resnet_v1_50/conv1/BatchNorm/gamma:0
restoring  resnet_v1_50/conv1/BatchNorm/moving_mean:0
restoring  resnet_v1_50/conv1/BatchNorm/moving_variance:0
restoring  resnet_v1_50/block1/unit_1/bottleneck_v1/shortcut/weights:0
restoring  resnet_v1_50/block1/unit_1/bottleneck_v1/shortcut/BatchNorm/beta:0
restoring  resnet_v1_50/block1/unit_1/bottleneck_v1/shortcut/BatchNorm/
。。。。。。
2017-07-13 08:23:30.197174: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
Checking your params ./data/pretrained_models/resnet_v1_50.ckpt
Traceback (most recent call last):
  File "train.py", line 339, in <module>
    train()
  File "train.py", line 245, in train
    restore(sess)
  File "train.py", line 154, in restore
    restorer.restore(sess, checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
     [[Node: save_1/RestoreV2_73 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_73/tensor_names, save_1/RestoreV2_73/shape_and_slices)]]
     [[Node: save_1/RestoreV2_163/_203 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_733_save_1/RestoreV2_163", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save_1/RestoreV2_73', defined at:
  File "train.py", line 339, in <module>
    train()
  File "train.py", line 245, in train
    restore(sess)
  File "train.py", line 153, in restore
    restorer = tf.train.Saver(vars_to_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
     [[Node: save_1/RestoreV2_73 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_73/tensor_names, save_1/RestoreV2_73/shape_and_slices)]]
     [[Node: save_1/RestoreV2_163/_203 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_733_save_1/RestoreV2_163", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
#######################
i look for some solution ，but i find this path "tensorflow/core/common_runtime/gpu/gpu_device.cc" can not be found，because /usr/local/lib/python2.7/dist-packages/tensorflow/core/  do not have "common_runtime "file.
please give some advice ,thanks a lot !

**Comment by lnuchiyo** [comment]
astromme/FastMaskRCNN@24cf5dd i have fixed it .thanks
but there is error in output when train:
P2
P3
P4
P5
anchor_scales =  [8, 16, 32]
anchor_scales =  [4, 8, 16]
anchor_scales =  [2, 4, 8]
anchor_scales =  [1, 2, 4]
5
4
3
2
/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2017-07-13 10:07:39.796796: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-13 10:07:39.796819: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-13 10:07:39.796823: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-13 10:07:39.796826: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-13 10:07:39.796847: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-07-13 10:07:39.879743: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-07-13 10:07:39.879958: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties: 
name: Quadro K620
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:01:00.0
Total memory: 1.95GiB
Free memory: 1.69GiB
2017-07-13 10:07:39.879970: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 
2017-07-13 10:07:39.879974: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y 
2017-07-13 10:07:39.879982: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro K620, pci bus id: 0000:01:00.0)
--restore_previous_if_exists is set, but failed to restore in ./output/mask_rcnn/ None
restoring  resnet_v1_50/conv1/weights:0
restoring  resnet_v1_50/conv1/BatchNorm/beta:0
restoring  resnet_v1_50/conv1/BatchNorm/gamma:0
restoring  resnet_v1_50/conv1/BatchNorm/moving_mean:0
restoring  resnet_v1_50/conv1/BatchNorm/moving_variance:0
restoring  resnet_v1_50/block1/unit_1/bottleneck_v1/shortcut/weights:0
restoring  resnet_v1_50/block1/unit_1/bottleneck_v1/shortcut/BatchNorm/beta:0
restoring  resnet_v1_50/block1/unit_1/bottleneck_v1/shortcut/BatchNorm/gamma:0
restoring  resnet_v1_50/block1/unit_1/bottleneck_v1/shortcut/BatchNorm/moving_mean:0
restoring  resnet_v1_50/block1/unit_1/bottleneck_v1/shortcut/BatchNorm/moving_variance:0
......
2017-07-13 10:07:50.700074: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
2017-07-13 10:07:50.700078: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
2017-07-13 10:07:50.700085: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
Checking your params ./data/pretrained_models/resnet_v1_50.ckpt
Traceback (most recent call last):
  File "train.py", line 339, in <module>
    train()
  File "train.py", line 245, in train
    restore(sess)
  File "train.py", line 154, in restore
    restorer.restore(sess, checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
	 [[Node: save_1/RestoreV2_72 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_72/tensor_names, save_1/RestoreV2_72/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_264/_541 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2140_save_1/RestoreV2_264", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save_1/RestoreV2_72', defined at:
  File "train.py", line 339, in <module>
    train()
  File "train.py", line 245, in train
    restore(sess)
  File "train.py", line 153, in restore
    restorer = tf.train.Saver(vars_to_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
	 [[Node: save_1/RestoreV2_72 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_72/tensor_names, save_1/RestoreV2_72/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_264/_541 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2140_save_1/RestoreV2_264", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
######
please give some advice ,thanks a lot !

**Comment by astromme** [comment]
It seems like you may not have downloaded the pretrained model and placed it in the pretrained_models directory. See this part of the readme:

> Download pretrained resnet50 model, wget http://download.tensorflow.org/models/resnet_v1_50_2016_08_28.tar.gz, unzip it, place it into ./data/pretrained_models/

FYI, for the OOM problem, you could try my fix from https://github.com/CharlesShang/FastMaskRCNN/issues/105

**Comment by lnuchiyo** [comment]
@astromme thanks ,  but i have placed this file in /FastMaskRCNN/data/pretrained_models,  this name is 'resnet_v1_50.ckpt'.

**Comment by xihanwei** [comment]
@lnuchiyo do you successfully train and evaluate the program on COCO ?

**Comment by xihanwei** [comment]
@lnuchiyo have you successfully trained and evaluated the program on COCO yet?

**Comment by landiaokafeiyan** [comment]
@lnuchiyo have you ｓｌｏｖｅ　the problem?　Ｉ　had the same problem with you.

**Comment by landiaokafeiyan** [comment]
@lnuchiyo I may the path problem,  Not found: ./data/pretrained_models, the path should be ./data/pretrained_models/,so the code can find the model, but i have no idea how to set the path

**Comment by xuw080** [comment]
You can set the path in configs/configs_v1.py

**Comment by minghaizhang** [comment]
You can set the path in configs/configs_v1.py
set the abs path  maybe solve the problems.
